# This is a basic workflow to help you get started with Actions

name: push_nuget

# on push on master
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Git Checkout
    - uses: actions/checkout@master
    
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1
      
    - name: Restore
      run: nuget restore src\Whatever\Whatever.sln
  
    - name: Build
      run: msbuild src\Whatever\Whatever.csproj
