# This is a basic workflow to help you get started with Actions

name: push_nuget

# on push on master
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@master
    
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
    
    - name: Publish
      uses: vvvv/PublishVLNuget@1.0.3-alpha
      with:
        NUSPEC: ./deployment/GithubPackageTest.nuspec
        SOLUTION: src\Whatever\Whatever.csproj
        ICON_SRC: https://raw.githubusercontent.com/vvvv/PublicContent/master/nugeticon.png
        ICON_DST: images
        VERSION: 2.0.0
        AUTO_PATCH_NUMBER: true
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
